import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0A0E1A' },
  loadingContainer: { flex: 1, backgroundColor: '#0A0E1A', justifyContent: 'center', alignItems: 'center', gap: 16 },
  loadingText: { color: '#94A3B8', fontSize: 14 },
  errorContainer: { flex: 1, backgroundColor: '#0A0E1A', justifyContent: 'center', alignItems: 'center', padding: 40, gap: 16 },
  errorTitle: { color: '#F8FAFC', fontSize: 20, fontWeight: '700' },
  errorDesc: { color: '#94A3B8', fontSize: 14, textAlign: 'center', marginBottom: 16 },
  retryBtn: { backgroundColor: '#38BDF8', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 10 },
  retryBtnText: { color: '#0F172A', fontWeight: '700' },
  caseHeader: { backgroundColor: '#1A1F2E', padding: 12, borderBottomLeftRadius: 16, borderBottomRightRadius: 16, borderBottomWidth: 1, borderBottomColor: '#38BDF830' },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  badge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#38BDF820', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, gap: 4 },
  badgeText: { color: '#38BDF8', fontSize: 11, fontWeight: '600' },
  timerBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#10B98120', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, gap: 4 },
  timerText: { color: '#10B981', fontSize: 11, fontWeight: '600' },
  dailyBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F59E0B15', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, gap: 4, alignSelf: 'flex-start', marginBottom: 8 },
  dailyBadgeText: { color: '#F59E0B', fontSize: 11, fontWeight: '600' },
  patientInfo: { color: '#38BDF8', fontWeight: 'bold', fontSize: 15, marginBottom: 2 },
  chiefComplaint: { color: '#F8FAFC', marginTop: 6, fontSize: 12, backgroundColor: '#F59E0B15', padding: 8, borderRadius: 6, borderLeftWidth: 2, borderLeftColor: '#F59E0B' },
  statsBar: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingVertical: 8, backgroundColor: '#0F172A', borderBottomWidth: 1, borderBottomColor: '#1E293B' },
  statItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  statText: { color: '#E2E8F0', fontSize: 12, fontWeight: '600' },
  hintBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F59E0B15', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, gap: 4 },
  hintBtnText: { color: '#F59E0B', fontSize: 11, fontWeight: '600' },
  chatArea: { flex: 1, padding: 12 },
  welcomeBubble: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#10B98115', padding: 12, borderRadius: 12, gap: 8, marginBottom: 12, borderWidth: 1, borderColor: '#10B98130' },
  welcomeText: { color: '#6EE7B7', fontSize: 13, flex: 1 },
  messageRow: { flexDirection: 'row', marginBottom: 8, alignItems: 'flex-end', gap: 6 },
  messageBubble: { padding: 10, borderRadius: 12, maxWidth: '75%' },
  requestBubble: { backgroundColor: '#3B82F6', alignSelf: 'flex-end' },
  responseBubble: { backgroundColor: '#1E293B', alignSelf: 'flex-start', borderWidth: 1, borderColor: '#334155' },
  hintBubble: { backgroundColor: '#F59E0B15', borderColor: '#F59E0B40' },
  messageText: { color: '#FFF', fontSize: 13, lineHeight: 18 },
  messageImage: { width: '100%', height: 200, borderRadius: 8, marginBottom: 6 },
  roleLabel: { fontSize: 8, fontWeight: '700', marginTop: 4, letterSpacing: 1 },
  aiIcon: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#10B98120', justifyContent: 'center', alignItems: 'center' },
  hintIcon: { backgroundColor: '#F59E0B20' },
  userIcon: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#3B82F620', justifyContent: 'center', alignItems: 'center' },
  menuTag: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 4 },
  menuTagText: { fontSize: 8, color: '#64748B', textTransform: 'uppercase' },
  loadingBubble: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1E293B80', padding: 10, borderRadius: 12, alignSelf: 'flex-start', gap: 8 },
  quickActions: { flexDirection: 'row', paddingHorizontal: 8, paddingVertical: 8, gap: 6, backgroundColor: '#0F172A', borderTopWidth: 1, borderTopColor: '#1E293B' },
  actionBtn: { flex: 1, backgroundColor: '#1E293B', padding: 10, alignItems: 'center', borderRadius: 12, flexDirection: 'row', justifyContent: 'center', gap: 4, borderWidth: 1, borderColor: 'transparent' },
  activeBtn: { backgroundColor: '#38BDF820', borderColor: '#38BDF8' },
  actionBtnText: { color: '#38BDF8', fontSize: 10, fontWeight: '600' },
  activeBtnText: { color: '#FFFFFF' },
  inputContainer: { paddingHorizontal: 12, paddingBottom: Platform.OS === 'ios' ? 30 : 12, paddingTop: 8, backgroundColor: '#0F172A', borderTopWidth: 1, borderTopColor: '#1E293B' },
  inputRow: { flexDirection: 'row', alignItems: 'flex-end', backgroundColor: '#1E293B', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 6, marginBottom: 8, borderWidth: 1, borderColor: '#334155' },
  textInput: { flex: 1, color: '#F8FAFC', fontSize: 13, maxHeight: 80 },
  sendBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#38BDF8', justifyContent: 'center', alignItems: 'center', marginLeft: 8 },
  sendBtnDisabled: { backgroundColor: '#334155' },
  finalDiagnosisBtn: { backgroundColor: '#10B981', padding: 14, borderRadius: 12, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8 },
  finalDiagnosisText: { color: '#0F172A', fontWeight: 'bold', fontSize: 14 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  menuContainer: { backgroundColor: '#1E293B', padding: 16, borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '70%' },
  menuHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#334155' },
  menuTitle: { color: '#F8FAFC', fontSize: 16, fontWeight: '700' },
  menuItem: { padding: 14, borderBottomWidth: 1, borderBottomColor: '#334155', flexDirection: 'row', alignItems: 'center', gap: 12 },
  menuItemText: { color: '#E2E8F0', flex: 1, fontSize: 14 },
  diagnosisContainer: { backgroundColor: '#1E293B', padding: 20, margin: 20, borderRadius: 20, borderWidth: 1, borderColor: '#334155' },
  diagnosisTitle: { color: '#F8FAFC', fontSize: 18, fontWeight: '700', marginBottom: 12 },
  diagnosisInput: { backgroundColor: '#0F172A', color: '#FFF', padding: 14, borderRadius: 12, minHeight: 80, fontSize: 14, borderWidth: 1, borderColor: '#334155' },
  diagnosisBtns: { flexDirection: 'row', gap: 8, marginTop: 16 },
  cancelBtn: { flex: 1, padding: 14, borderRadius: 12, backgroundColor: '#334155', alignItems: 'center' },
  cancelBtnText: { color: '#E2E8F0', fontWeight: '600' },
  submitBtn: { flex: 2, backgroundColor: '#10B981', padding: 14, alignItems: 'center', borderRadius: 12 },
  submitBtnDisabled: { opacity: 0.5 },
  submitBtnText: { color: '#0F172A', fontWeight: 'bold', fontSize: 14 },
  evaluatingOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center', gap: 16 },
  evaluatingText: { color: '#F8FAFC', fontSize: 16 },
  feedbackContainer: { backgroundColor: '#1E293B', padding: 20, margin: 20, borderRadius: 20, maxHeight: '70%', borderWidth: 1, borderColor: '#334155' },
  feedbackTitle: { color: '#F8FAFC', fontSize: 18, fontWeight: '700', marginBottom: 12, textAlign: 'center' },
  feedbackScroll: { maxHeight: 300 },
  feedbackText: { color: '#E2E8F0', fontSize: 14, lineHeight: 20 },
  closeFeedbackBtn: { backgroundColor: '#10B981', padding: 14, borderRadius: 12, alignItems: 'center', marginTop: 16 },
  closeFeedbackBtnText: { color: '#0F172A', fontWeight: 'bold', fontSize: 14 },
});
