import { BossCard } from './spacedRepetition';

export const ECG_BOSS_CARDS: BossCard[] = [
  {
    id: 'ecg_boss_1',
    question: 'A 65-year-old male presents with chest pain. ECG shows ST elevation in leads II, III, aVF with reciprocal ST depression in aVL. Which coronary artery is most likely occluded?',
    options: [
      { id: 'A', text: 'Left anterior descending (LAD)' },
      { id: 'B', text: 'Right coronary artery (RCA)' },
      { id: 'C', text: 'Left circumflex (LCx)' },
      { id: 'D', text: 'Left main coronary artery' },
    ],
    correctOptionId: 'B',
    explanation: 'ST elevation in inferior leads (II, III, aVF) indicates inferior MI, typically due to RCA occlusion (80%) or LCx (20%). Reciprocal changes in aVL confirm RCA involvement.',
    difficulty: 'hard',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_2',
    question: 'ECG shows wide QRS (>120ms), delta wave in lead II, and short PR interval. The patient has episodes of palpitations. What is the diagnosis?',
    options: [
      { id: 'A', text: 'LBBB' },
      { id: 'B', text: 'Wolff-Parkinson-White syndrome' },
      { id: 'C', text: 'Ventricular tachycardia' },
      { id: 'D', text: 'Hyperkalemia' },
    ],
    correctOptionId: 'B',
    explanation: 'Classic WPW triad: short PR (<120ms), delta wave (slurred upstroke of QRS), wide QRS (>120ms). Accessory pathway (Bundle of Kent) bypasses AV node causing pre-excitation.',
    difficulty: 'hard',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_3',
    question: 'A 45-year-old female with syncope. ECG shows ST elevation in V1-V3 with RBBB pattern and T-wave inversion. What is the most likely diagnosis?',
    options: [
      { id: 'A', text: 'Anterior STEMI' },
      { id: 'B', text: 'Brugada syndrome' },
      { id: 'C', text: 'Pericarditis' },
      { id: 'D', text: 'Pulmonary embolism' },
    ],
    correctOptionId: 'B',
    explanation: 'Brugada Type 1: Coved ST elevation ≥2mm in V1-V3 followed by T-wave inversion. RBBB pattern may be present. Associated with sudden cardiac death, especially in young Asian males.',
    difficulty: 'expert',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_4',
    question: 'ECG shows low voltage QRS complexes, electrical alternans, and sinus tachycardia. Patient has hypotension and distended neck veins. Diagnosis?',
    options: [
      { id: 'A', text: 'Constrictive pericarditis' },
      { id: 'B', text: 'Cardiac tamponade' },
      { id: 'C', text: 'Dilated cardiomyopathy' },
      { id: 'D', text: 'Massive pulmonary embolism' },
    ],
    correctOptionId: 'B',
    explanation: 'Electrical alternans (alternating QRS amplitude) + low voltage + sinus tachycardia = cardiac tamponade (Beck triad: hypotension, muffled heart sounds, JVD). ECG shows swinging heart in pericardial effusion.',
    difficulty: 'hard',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_5',
    question: 'A 30-year-old with chest pain, fever, and pericardial rub. ECG shows diffuse ST elevation in all leads except aVR and V1, with PR depression. What is it?',
    options: [
      { id: 'A', text: 'Acute STEMI' },
      { id: 'B', text: 'Acute pericarditis' },
      { id: 'C', text: 'Early repolarization' },
      { id: 'D', text: 'Myocarditis' },
    ],
    correctOptionId: 'B',
    explanation: 'Classic pericarditis: diffuse ST elevation (concave up) in most leads, PR depression, ST elevation in II > III, no reciprocal changes. Unlike STEMI, ST elevation is widespread and not territorial.',
    difficulty: 'hard',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_6',
    question: 'ECG: Wide QRS complex tachycardia at 180 bpm. No clear P waves. QRS >140ms. Patient is hemodynamically stable. What is the FIRST step?',
    options: [
      { id: 'A', text: 'Immediate cardioversion' },
      { id: 'B', text: 'IV adenosine' },
      { id: 'C', text: 'IV amiodarone' },
      { id: 'D', text: 'Vagal maneuvers then adenosine' },
    ],
    correctOptionId: 'C',
    explanation: 'Wide complex tachycardia = treat as VT until proven otherwise. If stable: IV amiodarone 150mg over 10 min. If unstable: synchronized cardioversion. Adenosine can help diagnose but may cause degeneration to VF.',
    difficulty: 'expert',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_7',
    question: 'ECG: Prolonged QT interval (QTc >500ms) with T-wave alternans. Patient on multiple medications. Which drug is LEAST likely to cause this?',
    options: [
      { id: 'A', text: 'Amiodarone' },
      { id: 'B', text: 'Haloperidol' },
      { id: 'C', text: 'Azithromycin' },
      { id: 'D', text: 'Metoprolol' },
    ],
    correctOptionId: 'D',
    explanation: 'Metoprolol (beta-blocker) does NOT prolong QT. Amiodarone, haloperidol, azithromycin, methadone, fluoroquinolones all prolong QT. T-wave alternans = beat-to-beat variation in T-wave morphology = high risk for Torsades de Pointes.',
    difficulty: 'expert',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_8',
    question: '78-year-old with bradycardia. ECG: No relationship between P waves and QRS complexes. Atrial rate 80, ventricular rate 35. What is it?',
    options: [
      { id: 'A', text: 'Sinus bradycardia' },
      { id: 'B', text: 'Mobitz II AV block' },
      { id: 'C', text: 'Third-degree (complete) AV block' },
      { id: 'D', text: 'Atrial fibrillation with slow response' },
    ],
    correctOptionId: 'C',
    explanation: 'Complete heart block: AV dissociation (P waves and QRS completely independent), atrial rate > ventricular rate. Treatment: pacemaker (temporary then permanent). Reversible causes: hyperkalemia, ischemia, Lyme disease.',
    difficulty: 'hard',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_9',
    question: 'ECG in a young athlete: ST elevation in precordial leads, T-wave inversion, but no symptoms. Which finding suggests ARVD rather than benign early repolarization?',
    options: [
      { id: 'A', text: 'ST elevation in V2-V4' },
      { id: 'B', text: 'Epsilon wave in V1-V3' },
      { id: 'C', text: 'J-point elevation' },
      { id: 'D', text: 'Sinus bradycardia' },
    ],
    correctOptionId: 'B',
    explanation: 'Epsilon wave (small positive deflection after QRS, before T wave in V1-V3) is pathognomonic for ARVD (Arrhythmogenic Right Ventricular Dysplasia). ARVD = fibrofatty replacement of RV myocardium, can cause sudden death in young athletes.',
    difficulty: 'expert',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_10',
    question: 'ECG shows peaked T waves, loss of P waves, and wide QRS (>160ms). Serum potassium is 7.2 mEq/L. What\'s the IMMEDIATE treatment?',
    options: [
      { id: 'A', text: 'IV sodium bicarbonate' },
      { id: 'B', text: 'IV calcium gluconate' },
      { id: 'C', text: 'IV insulin + glucose' },
      { id: 'D', text: 'Kayexalate orally' },
    ],
    correctOptionId: 'B',
    explanation: 'Calcium gluconate FIRST (cardioprotective, stabilizes myocardium). Then shift K+ intracellularly: IV insulin + D50, sodium bicarbonate, albuterol. Then eliminate: furosemide, dialysis, Kayexalate. Calcium does NOT lower K+, only protects the heart.',
    difficulty: 'hard',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_11',
    question: 'Acute chest pain patient. ECG: Deep symmetrical T-wave inversion in V1-V4 without ST elevation. What\'s the most concerning diagnosis?',
    options: [
      { id: 'A', text: 'Non-STEMI' },
      { id: 'B', text: 'Wellens syndrome (LAD stenosis)' },
      { id: 'C', text: 'Takotsubo cardiomyopathy' },
      { id: 'D', text: 'Subarachnoid hemorrhage' },
    ],
    correctOptionId: 'B',
    explanation: 'Wellens Syndrome: Deep symmetric T-wave inversion (Type B) or biphasic T waves (Type A) in V1-V4 = critical proximal LAD stenosis. These patients are at HIGH risk for anterior STEMI. Needs urgent cath, NOT stress test!',
    difficulty: 'expert',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_12',
    question: 'ECG in a patient with pacemaker: Spikes before each QRS but no capture. What\'s the first thing to check?',
    options: [
      { id: 'A', text: 'Check electrolytes (K+, Ca++)' },
      { id: 'B', text: 'Chest X-ray for lead displacement' },
      { id: 'C', text: 'Pacemaker interrogation' },
      { id: 'D', text: 'Magnet application' },
    ],
    correctOptionId: 'A',
    explanation: 'Pacemaker spikes without capture = failure to capture. Common causes: hyperkalemia, lead fracture/displacement, battery depletion, myocardial infarction at lead site. Check K+ first (easily reversible). Then CXR + interrogation.',
    difficulty: 'hard',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_13',
    question: 'Young patient with palpitations. ECG: Irregularly irregular rhythm, no P waves, QRS rate 120-160. Delta waves visible. What\'s the rhythm?',
    options: [
      { id: 'A', text: 'Atrial fibrillation in WPW' },
      { id: 'B', text: 'Multifocal atrial tachycardia' },
      { id: 'C', text: 'Atrial flutter with variable block' },
      { id: 'D', text: 'Sinus tachycardia with PVCs' },
    ],
    correctOptionId: 'A',
    explanation: 'AFib in WPW = dangerous! AV conduction through accessory pathway (no delay) → extremely rapid ventricular rates (may degenerate to VF). NEVER give AV nodal blockers (beta-blockers, CCB, digoxin, adenosine). Treatment: procainamide or cardioversion.',
    difficulty: 'expert',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_14',
    question: 'ECG: Osborn wave (J wave) at J-point, prolonged PR, and artifact from shivering. Core temperature 30°C (86°F). What rhythm is this?',
    options: [
      { id: 'A', text: 'Osborn wave of hypothermia' },
      { id: 'B', text: 'Benign early repolarization' },
      { id: 'C', text: 'STEMI with hypothermia' },
      { id: 'D', text: 'Pericarditis' },
    ],
    correctOptionId: 'A',
    explanation: 'Osborn (J) wave = positive deflection at J-point, seen in hypothermia (<32°C). Other hypothermia ECG changes: bradycardia, prolonged PR/QT/QRS, atrial fib, shivering artifact. Rewarm patient!',
    difficulty: 'hard',
    timeLimit: 45,
  },
  {
    id: 'ecg_boss_15',
    question: 'Chest pain with normal ECG and normal troponin x2. But high pretest probability. What\'s the BEST next step?',
    options: [
      { id: 'A', text: 'Discharge with PPI for GERD' },
      { id: 'B', text: 'CT coronary angiography' },
      { id: 'C', text: 'Stress test (exercise or pharmacologic)' },
      { id: 'D', text: 'Repeat troponin in 6 hours and echo' },
    ],
    correctOptionId: 'C',
    explanation: 'Normal ECG + normal troponin x2 in high-risk patient → stress testing (preferred over CCTA for functional assessment). CCTA if stress test equivocal. Never dismiss chest pain based on normal initial workup in high-risk patients.',
    difficulty: 'hard',
    timeLimit: 45,
  },
];
