import { StyleSheet, Text, View, ScrollView, Pressable } from 'react-native';
import { useRouter } from 'expo-router';
import { useStore } from '../../../src/store';
export default function Profile() {
  const router = useRouter();
  const { totalPoints, completedCases } = useStore();
  const acc = completedCases.length > 0 ? Math.round(completedCases.reduce((a, c) => a + c.score, 0) / completedCases.length) : 0;
  return (<ScrollView style={s.c}><Text style={s.t}>Profile</Text><View style={s.card}><Text style={s.av}>🩺</Text><Text style={s.name}>Dr. Ahmed</Text><Text style={s.role}>Resident</Text></View><View style={s.row}><View style={s.st}><Text style={s.sv}>{totalPoints}</Text><Text style={s.sl}>Points</Text></View><View style={s.st}><Text style={s.sv}>{completedCases.length}</Text><Text style={s.sl}>Cases</Text></View><View style={s.st}><Text style={s.sv}>{acc}%</Text><Text style={s.sl}>Accuracy</Text></View></View><Pressable style={s.btn} onPress={() => router.push('/profile/edit')}><Text style={s.bt}>Edit Profile</Text></Pressable><Pressable style={s.btn} onPress={() => router.push('/profile/history')}><Text style={s.bt}>History</Text></Pressable><Pressable style={s.btn} onPress={() => router.push('/settings')}><Text style={s.bt}>Settings</Text></Pressable></ScrollView>);
}
const s = StyleSheet.create({ c: { flex: 1, backgroundColor: '#0A0E1A' }, t: { color: '#F8FAFC', fontSize: 24, fontWeight: '800', padding: 20 }, card: { backgroundColor: '#1E293B', margin: 16, padding: 24, borderRadius: 20, alignItems: 'center', borderWidth: 1, borderColor: '#334155' }, av: { fontSize: 48, marginBottom: 8 }, name: { color: '#F8FAFC', fontSize: 20, fontWeight: '800' }, role: { color: '#94A3B8', fontSize: 13 }, row: { flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 16 }, st: { flex: 1, backgroundColor: '#1E293B', padding: 14, borderRadius: 14, alignItems: 'center', borderWidth: 1, borderColor: '#334155' }, sv: { color: '#F8FAFC', fontSize: 20, fontWeight: '800' }, sl: { color: '#94A3B8', fontSize: 10, marginTop: 2 }, btn: { backgroundColor: '#1E293B', marginHorizontal: 16, marginBottom: 6, padding: 14, borderRadius: 14, borderWidth: 1, borderColor: '#334155', alignItems: 'center' }, bt: { color: '#38BDF8', fontSize: 14, fontWeight: '600' } });
